List<Map<String, dynamic>> ticketList = [
  {
    'from': {'code': 'NYC', 'name': 'New-York'},
    'to': {'code': 'LDN', 'name': 'London'},
    'flying_time': '8H 30M',
    'date': '1 MAY',
    'departure_time': '08:00 AM',
    'number': 23,
  },
  {
    'from': {'code': 'DK', 'name': 'Dhaka'},
    'to': {'code': 'NYC', 'name': 'New-York'},
    'flying_time': '6H 10M',
    'date': '2 MAY',
    'departure_time': '09:15 AM',
    'number': 45,
  },
  {
    'from': {'code': 'DXB', 'name': 'Dubai'},
    'to': {'code': 'CAI', 'name': 'Cairo'},
    'flying_time': '4H 50M',
    'date': '3 MAY',
    'departure_time': '10:30 AM',
    'number': 12,
  },
  {
    'from': {'code': 'LOS', 'name': 'Lagos'},
    'to': {'code': 'ABJ', 'name': 'Abuja'},
    'flying_time': '1H 15M',
    'date': '4 MAY',
    'departure_time': '07:00 AM',
    'number': 98,
  },
  {
    'from': {'code': 'KRT', 'name': 'Khartoum'},
    'to': {'code': 'NBO', 'name': 'Nairobi'},
    'flying_time': '3H 05M',
    'date': '5 MAY',
    'departure_time': '01:20 PM',
    'number': 7,
  },
  {
    'from': {'code': 'ACC', 'name': 'Accra'},
    'to': {'code': 'DUB', 'name': 'Dublin'},
    'flying_time': '7H 40M',
    'date': '6 MAY',
    'departure_time': '11:45 AM',
    'number': 53,
  },
  {
    'from': {'code': 'FRA', 'name': 'Frankfurt'},
    'to': {'code': 'PAR', 'name': 'Paris'},
    'flying_time': '1H 05M',
    'date': '7 MAY',
    'departure_time': '04:00 PM',
    'number': 34,
  },
  {
    'from': {'code': 'MAD', 'name': 'Madrid'},
    'to': {'code': 'ROM', 'name': 'Rome'},
    'flying_time': '2H 10M',
    'date': '8 MAY',
    'departure_time': '06:30 PM',
    'number': 61,
  },
  {
    'from': {'code': 'BER', 'name': 'Berlin'},
    'to': {'code': 'AMS', 'name': 'Amsterdam'},
    'flying_time': '1H 00M',
    'date': '9 MAY',
    'departure_time': '02:45 PM',
    'number': 29,
  },
  {
    'from': {'code': 'LIS', 'name': 'Lisbon'},
    'to': {'code': 'BRU', 'name': 'Brussels'},
    'flying_time': '2H 20M',
    'date': '10 MAY',
    'departure_time': '05:55 PM',
    'number': 81,
  },
  {
    'from': {'code': 'STO', 'name': 'Stockholm'},
    'to': {'code': 'OSL', 'name': 'Oslo'},
    'flying_time': '1H 25M',
    'date': '11 MAY',
    'departure_time': '09:00 AM',
    'number': 14,
  },
  {
    'from': {'code': 'CPH', 'name': 'Copenhagen'},
    'to': {'code': 'HEL', 'name': 'Helsinki'},
    'flying_time': '1H 35M',
    'date': '12 MAY',
    'departure_time': '10:10 AM',
    'number': 20,
  },
  {
    'from': {'code': 'ZRH', 'name': 'Zurich'},
    'to': {'code': 'VIE', 'name': 'Vienna'},
    'flying_time': '1H 50M',
    'date': '13 MAY',
    'departure_time': '11:30 AM',
    'number': 47,
  },
  {
    'from': {'code': 'BCN', 'name': 'Barcelona'},
    'to': {'code': 'MUC', 'name': 'Munich'},
    'flying_time': '2H 05M',
    'date': '14 MAY',
    'departure_time': '03:15 PM',
    'number': 56,
  },
  {
    'from': {'code': 'ATH', 'name': 'Athens'},
    'to': {'code': 'IST', 'name': 'Istanbul'},
    'flying_time': '1H 45M',
    'date': '15 MAY',
    'departure_time': '07:40 PM',
    'number': 68,
  },
  {
    'from': {'code': 'SVO', 'name': 'Moscow'},
    'to': {'code': 'LED', 'name': 'St. Petersburg'},
    'flying_time': '1H 10M',
    'date': '16 MAY',
    'departure_time': '08:20 AM',
    'number': 5,
  },
  {
    'from': {'code': 'JFK', 'name': 'New York JFK'},
    'to': {'code': 'BOS', 'name': 'Boston'},
    'flying_time': '1H 30M',
    'date': '17 MAY',
    'departure_time': '12:00 PM',
    'number': 99,
  },
  {
    'from': {'code': 'SFO', 'name': 'San Francisco'},
    'to': {'code': 'LAX', 'name': 'Los Angeles'},
    'flying_time': '1H 25M',
    'date': '18 MAY',
    'departure_time': '02:00 PM',
    'number': 33,
  },
  {
    'from': {'code': 'SEA', 'name': 'Seattle'},
    'to': {'code': 'PDX', 'name': 'Portland'},
    'flying_time': '0H 50M',
    'date': '19 MAY',
    'departure_time': '06:45 PM',
    'number': 22,
  },
  {
    'from': {'code': 'MIA', 'name': 'Miami'},
    'to': {'code': 'ATL', 'name': 'Atlanta'},
    'flying_time': '1H 40M',
    'date': '20 MAY',
    'departure_time': '05:30 PM',
    'number': 72,
  },
  {
    'from': {'code': 'YYZ', 'name': 'Toronto'},
    'to': {'code': 'YVR', 'name': 'Vancouver'},
    'flying_time': '5H 15M',
    'date': '21 MAY',
    'departure_time': '09:50 AM',
    'number': 11,
  },
  {
    'from': {'code': 'YYC', 'name': 'Calgary'},
    'to': {'code': 'YQT', 'name': 'Thunder Bay'},
    'flying_time': '2H 25M',
    'date': '22 MAY',
    'departure_time': '01:15 PM',
    'number': 40,
  },
  {
    'from': {'code': 'SCL', 'name': 'Santiago'},
    'to': {'code': 'LIM', 'name': 'Lima'},
    'flying_time': '3H 35M',
    'date': '23 MAY',
    'departure_time': '08:10 AM',
    'number': 59,
  },
  {
    'from': {'code': 'EZE', 'name': 'Buenos Aires'},
    'to': {'code': 'GRU', 'name': 'Sao Paulo'},
    'flying_time': '2H 55M',
    'date': '24 MAY',
    'departure_time': '11:00 AM',
    'number': 86,
  },
  {
    'from': {'code': 'GIG', 'name': 'Rio de Janeiro'},
    'to': {'code': 'BOG', 'name': 'Bogota'},
    'flying_time': '5H 05M',
    'date': '25 MAY',
    'departure_time': '03:45 PM',
    'number': 9,
  },
  {
    'from': {'code': 'CPT', 'name': 'Cape Town'},
    'to': {'code': 'JNB', 'name': 'Johannesburg'},
    'flying_time': '2H 00M',
    'date': '26 MAY',
    'departure_time': '07:30 PM',
    'number': 64,
  },
  {
    'from': {'code': 'KGL', 'name': 'Kigali'},
    'to': {'code': 'LBV', 'name': 'Libreville'},
    'flying_time': '3H 20M',
    'date': '27 MAY',
    'departure_time': '10:00 AM',
    'number': 26,
  },
  {
    'from': {'code': 'DAR', 'name': 'Dar es Salaam'},
    'to': {'code': 'MMB', 'name': 'Moroni'},
    'flying_time': '2H 40M',
    'date': '28 MAY',
    'departure_time': '12:20 PM',
    'number': 71,
  },
  {
    'from': {'code': 'HKG', 'name': 'Hong Kong'},
    'to': {'code': 'BKK', 'name': 'Bangkok'},
    'flying_time': '2H 55M',
    'date': '29 MAY',
    'departure_time': '09:00 AM',
    'number': 36,
  },
  {
    'from': {'code': 'SIN', 'name': 'Singapore'},
    'to': {'code': 'KUL', 'name': 'Kuala Lumpur'},
    'flying_time': '1H 05M',
    'date': '30 MAY',
    'departure_time': '02:50 PM',
    'number': 52,
  },
  {
    'from': {'code': 'NRT', 'name': 'Tokyo Narita'},
    'to': {'code': 'HND', 'name': 'Tokyo Haneda'},
    'flying_time': '0H 35M',
    'date': '31 MAY',
    'departure_time': '06:00 PM',
    'number': 18,
  },
  {
    'from': {'code': 'ICN', 'name': 'Seoul Incheon'},
    'to': {'code': 'GMP', 'name': 'Seoul Gimpo'},
    'flying_time': '0H 45M',
    'date': '1 JUN',
    'departure_time': '08:30 AM',
    'number': 44,
  },
  {
    'from': {'code': 'BOM', 'name': 'Mumbai'},
    'to': {'code': 'DEL', 'name': 'New Delhi'},
    'flying_time': '2H 10M',
    'date': '2 JUN',
    'departure_time': '11:15 AM',
    'number': 77,
  },
  {
    'from': {'code': 'BLR', 'name': 'Bengaluru'},
    'to': {'code': 'MAA', 'name': 'Chennai'},
    'flying_time': '1H 20M',
    'date': '3 JUN',
    'departure_time': '01:40 PM',
    'number': 31,
  },
  {
    'from': {'code': 'KTM', 'name': 'Kathmandu'},
    'to': {'code': 'LHE', 'name': 'Lahore'},
    'flying_time': '2H 50M',
    'date': '4 JUN',
    'departure_time': '05:00 PM',
    'number': 63,
  },
  {
    'from': {'code': 'ISB', 'name': 'Islamabad'},
    'to': {'code': 'KHI', 'name': 'Karachi'},
    'flying_time': '1H 10M',
    'date': '5 JUN',
    'departure_time': '07:10 AM',
    'number': 4,
  },
  {
    'from': {'code': 'MEL', 'name': 'Melbourne'},
    'to': {'code': 'SYD', 'name': 'Sydney'},
    'flying_time': '1H 30M',
    'date': '6 JUN',
    'departure_time': '09:45 AM',
    'number': 90,
  },
  {
    'from': {'code': 'AKL', 'name': 'Auckland'},
    'to': {'code': 'WLG', 'name': 'Wellington'},
    'flying_time': '1H 05M',
    'date': '7 JUN',
    'departure_time': '11:00 AM',
    'number': 58,
  },
  {
    'from': {'code': 'PEK', 'name': 'Beijing'},
    'to': {'code': 'PVG', 'name': 'Shanghai Pudong'},
    'flying_time': '2H 10M',
    'date': '8 JUN',
    'departure_time': '03:30 PM',
    'number': 42,
  },
  {
    'from': {'code': 'CAN', 'name': 'Guangzhou'},
    'to': {'code': 'SZX', 'name': 'Shenzhen'},
    'flying_time': '0H 45M',
    'date': '9 JUN',
    'departure_time': '06:20 PM',
    'number': 27,
  },
  {
    'from': {'code': 'MNL', 'name': 'Manila'},
    'to': {'code': 'CEB', 'name': 'Cebu'},
    'flying_time': '1H 20M',
    'date': '10 JUN',
    'departure_time': '08:00 AM',
    'number': 69,
  },
  {
    'from': {'code': 'HND', 'name': 'Tokyo Haneda'},
    'to': {'code': 'CTS', 'name': 'Sapporo'},
    'flying_time': '1H 50M',
    'date': '11 JUN',
    'departure_time': '12:15 PM',
    'number': 6,
  },
  {
    'from': {'code': 'COK', 'name': 'Kochi'},
    'to': {'code': 'GAU', 'name': 'Guwahati'},
    'flying_time': '2H 00M',
    'date': '12 JUN',
    'departure_time': '02:30 PM',
    'number': 84,
  },
  {
    'from': {'code': 'RIX', 'name': 'Riga'},
    'to': {'code': 'TLL', 'name': 'Tallinn'},
    'flying_time': '0H 55M',
    'date': '13 JUN',
    'departure_time': '04:40 PM',
    'number': 17,
  },
  {
    'from': {'code': 'VNO', 'name': 'Vilnius'},
    'to': {'code': 'RZE', 'name': 'Rzeszow'},
    'flying_time': '1H 15M',
    'date': '14 JUN',
    'departure_time': '06:00 PM',
    'number': 50,
  },
  {
    'from': {'code': 'SJJ', 'name': 'Sarajevo'},
    'to': {'code': 'PRN', 'name': 'Pristina'},
    'flying_time': '1H 05M',
    'date': '15 JUN',
    'departure_time': '07:30 AM',
    'number': 35,
  },
  {
    'from': {'code': 'BEG', 'name': 'Belgrade'},
    'to': {'code': 'SKP', 'name': 'Skopje'},
    'flying_time': '0H 50M',
    'date': '16 JUN',
    'departure_time': '09:10 AM',
    'number': 2,
  },
  {
    'from': {'code': 'TBS', 'name': 'Tbilisi'},
    'to': {'code': 'Yere', 'name': 'Yerevan'},
    'flying_time': '1H 25M',
    'date': '17 JUN',
    'departure_time': '11:55 AM',
    'number': 38,
  },
];

List<Map<String, dynamic>> hotelList = [
  {
    'image': '1.jpg',
    'place': 'Open Space',
    'destination': 'London',
    'price': 25,
  },
  {
    'image': '2.jpg',
    'place': 'Global Will',
    'destination': 'London',
    'price': 40,
  },
  {
    'image': '3.jpg',
    'place': 'Tallest Building',
    'destination': 'Dubai',
    'price': 68,
  },
  {
    'image': '4.jpg',
    'place': 'Place 4',
    'destination': 'New York',
    'price': 55,
  },
  {'image': '5.jpg', 'place': 'Place 5', 'destination': 'Paris', 'price': 60},
  {'image': '6.jpg', 'place': 'Place 6', 'destination': 'Tokyo', 'price': 72},
  {'image': '7.jpg', 'place': 'Place 7', 'destination': 'Lagos', 'price': 30},
  {'image': '8.jpg', 'place': 'Place 8', 'destination': 'Cairo', 'price': 28},
  {'image': '9.jpg', 'place': 'Place 9', 'destination': 'Berlin', 'price': 45},
  {'image': '10.jpg', 'place': 'Place 10', 'destination': 'Rome', 'price': 50},
  {
    'image': '11.jpg',
    'place': 'Place 11',
    'destination': 'Madrid',
    'price': 42,
  },
  {
    'image': '12.jpg',
    'place': 'Place 12',
    'destination': 'Amsterdam',
    'price': 48,
  },
  {
    'image': '13.jpg',
    'place': 'Place 13',
    'destination': 'Istanbul',
    'price': 65,
  },
  {
    'image': '14.jpg',
    'place': 'Place 14',
    'destination': 'Athens',
    'price': 38,
  },
  {
    'image': '15.jpg',
    'place': 'Place 15',
    'destination': 'Prague',
    'price': 35,
  },
  {
    'image': '16.jpg',
    'place': 'Place 16',
    'destination': 'Lisbon',
    'price': 36,
  },
  {
    'image': '17.jpg',
    'place': 'Place 17',
    'destination': 'Brussels',
    'price': 44,
  },
  {
    'image': '18.jpg',
    'place': 'Place 18',
    'destination': 'Vienna',
    'price': 58,
  },
  {
    'image': '19.jpg',
    'place': 'Place 19',
    'destination': 'Zurich',
    'price': 80,
  },
  {
    'image': '20.jpg',
    'place': 'Place 20',
    'destination': 'Stockholm',
    'price': 70,
  },
  {'image': '21.jpg', 'place': 'Place 21', 'destination': 'Oslo', 'price': 68},
  {
    'image': '22.jpg',
    'place': 'Place 22',
    'destination': 'Helsinki',
    'price': 66,
  },
  {
    'image': '23.jpg',
    'place': 'Place 23',
    'destination': 'Copenhagen',
    'price': 62,
  },
  {
    'image': '24.jpg',
    'place': 'Place 24',
    'destination': 'Munich',
    'price': 54,
  },
  {
    'image': '25.jpg',
    'place': 'Place 25',
    'destination': 'Barcelona',
    'price': 49,
  },
  {
    'image': '26.jpg',
    'place': 'Place 26',
    'destination': 'Edinburgh',
    'price': 46,
  },
  {'image': '1.jpg', 'place': 'Place 27', 'destination': 'Dublin', 'price': 41},
  {'image': '2.jpg', 'place': 'Place 28', 'destination': 'Bergen', 'price': 39},
  {
    'image': '3.jpg',
    'place': 'Place 29',
    'destination': 'Reykjavik',
    'price': 90,
  },
  {'image': '4.jpg', 'place': 'Place 30', 'destination': 'Warsaw', 'price': 34},
  {
    'image': '5.jpg',
    'place': 'Place 31',
    'destination': 'Budapest',
    'price': 33,
  },
  {'image': '6.jpg', 'place': 'Place 32', 'destination': 'Sofia', 'price': 29},
  {
    'image': '7.jpg',
    'place': 'Place 33',
    'destination': 'Belgrade',
    'price': 27,
  },
  {'image': '8.jpg', 'place': 'Place 34', 'destination': 'Zagreb', 'price': 31},
  {
    'image': '9.jpg',
    'place': 'Place 35',
    'destination': 'Ljubljana',
    'price': 28,
  },
  {
    'image': '10.jpg',
    'place': 'Place 36',
    'destination': 'Tallinn',
    'price': 26,
  },
  {'image': '11.jpg', 'place': 'Place 37', 'destination': 'Riga', 'price': 24},
  {
    'image': '12.jpg',
    'place': 'Place 38',
    'destination': 'Vilnius',
    'price': 25,
  },
  {
    'image': '13.jpg',
    'place': 'Place 39',
    'destination': 'Skopje',
    'price': 23,
  },
  {
    'image': '14.jpg',
    'place': 'Place 40',
    'destination': 'Prague',
    'price': 37,
  },
  {
    'image': '15.jpg',
    'place': 'Place 41',
    'destination': 'Bratislava',
    'price': 32,
  },
  {
    'image': '16.jpg',
    'place': 'Place 42',
    'destination': 'Kosice',
    'price': 22,
  },
  {'image': '17.jpg', 'place': 'Place 43', 'destination': 'Cluj', 'price': 21},
  {
    'image': '18.jpg',
    'place': 'Place 44',
    'destination': 'Timisoara',
    'price': 20,
  },
  {
    'image': '19.jpg',
    'place': 'Place 45',
    'destination': 'Bucharest',
    'price': 30,
  },
  {
    'image': '20.jpg',
    'place': 'Place 46',
    'destination': 'Chisinau',
    'price': 19,
  },
  {
    'image': '21.jpg',
    'place': 'Place 47',
    'destination': 'Tirana',
    'price': 18,
  },
  {
    'image': '22.jpg',
    'place': 'Place 48',
    'destination': 'Skopje',
    'price': 17,
  },
  {
    'image': '23.jpg',
    'place': 'Place 49',
    'destination': 'Sarajevo',
    'price': 16,
  },
  {
    'image': '24.jpg',
    'place': 'Place 50',
    'destination': 'Podgorica',
    'price': 15,
  },
  {
    'image': '25.jpg',
    'place': 'Place 51',
    'destination': 'Zagreb',
    'price': 35,
  },
  {
    'image': '26.jpg',
    'place': 'Place 52',
    'destination': 'Dubrovnik',
    'price': 48,
  },
  {'image': '1.jpg', 'place': 'Place 53', 'destination': 'Split', 'price': 43},
  {'image': '2.jpg', 'place': 'Place 54', 'destination': 'Athens', 'price': 60},
  {
    'image': '3.jpg',
    'place': 'Place 55',
    'destination': 'Thessaloniki',
    'price': 38,
  },
  {
    'image': '4.jpg',
    'place': 'Place 56',
    'destination': 'Heraklion',
    'price': 46,
  },
  {
    'image': '5.jpg',
    'place': 'Place 57',
    'destination': 'Santorini',
    'price': 120,
  },
  {
    'image': '6.jpg',
    'place': 'Place 58',
    'destination': 'Mykonos',
    'price': 110,
  },
  {'image': '7.jpg', 'place': 'Place 59', 'destination': 'Rhodes', 'price': 70},
  {'image': '8.jpg', 'place': 'Place 60', 'destination': 'Corfu', 'price': 65},
  {
    'image': '9.jpg',
    'place': 'Place 61',
    'destination': 'Valletta',
    'price': 55,
  },
  {'image': '10.jpg', 'place': 'Place 62', 'destination': 'Gozo', 'price': 40},
  {'image': '11.jpg', 'place': 'Place 63', 'destination': 'Rabat', 'price': 28},
  {
    'image': '12.jpg',
    'place': 'Place 64',
    'destination': 'Casablanca',
    'price': 33,
  },
  {
    'image': '13.jpg',
    'place': 'Place 65',
    'destination': 'Marrakesh',
    'price': 50,
  },
  {'image': '14.jpg', 'place': 'Place 66', 'destination': 'Fes', 'price': 27},
  {
    'image': '15.jpg',
    'place': 'Place 67',
    'destination': 'Agadir',
    'price': 35,
  },
  {
    'image': '16.jpg',
    'place': 'Place 68',
    'destination': 'Tangier',
    'price': 30,
  },
  {
    'image': '17.jpg',
    'place': 'Place 69',
    'destination': 'Essaouira',
    'price': 29,
  },
  {'image': '18.jpg', 'place': 'Place 70', 'destination': 'Dakar', 'price': 45},
  {
    'image': '19.jpg',
    'place': 'Place 71',
    'destination': 'Banjul',
    'price': 34,
  },
  {
    'image': '20.jpg',
    'place': 'Place 72',
    'destination': 'Freetown',
    'price': 22,
  },
  {
    'image': '21.jpg',
    'place': 'Place 73',
    'destination': 'Monrovia',
    'price': 25,
  },
  {
    'image': '22.jpg',
    'place': 'Place 74',
    'destination': 'Abidjan',
    'price': 48,
  },
  {'image': '23.jpg', 'place': 'Place 75', 'destination': 'Accra', 'price': 40},
  {
    'image': '24.jpg',
    'place': 'Place 76',
    'destination': 'Kigali',
    'price': 36,
  },
  {
    'image': '25.jpg',
    'place': 'Place 77',
    'destination': 'Kampala',
    'price': 28,
  },
  {
    'image': '26.jpg',
    'place': 'Place 78',
    'destination': 'Harare',
    'price': 26,
  },
  {'image': '1.jpg', 'place': 'Place 79', 'destination': 'Lusaka', 'price': 24},
  {
    'image': '2.jpg',
    'place': 'Place 80',
    'destination': 'Windhoek',
    'price': 32,
  },
  {'image': '3.jpg', 'place': 'Place 81', 'destination': 'Maputo', 'price': 30},
  {
    'image': '4.jpg',
    'place': 'Place 82',
    'destination': 'Lilongwe',
    'price': 20,
  },
  {
    'image': '5.jpg',
    'place': 'Place 83',
    'destination': 'Mauritius',
    'price': 95,
  },
  {
    'image': '6.jpg',
    'place': 'Place 84',
    'destination': 'Seychelles',
    'price': 150,
  },
  {
    'image': '7.jpg',
    'place': 'Place 85',
    'destination': 'Maldives',
    'price': 200,
  },
  {'image': '8.jpg', 'place': 'Place 86', 'destination': 'Phuket', 'price': 85},
  {'image': '9.jpg', 'place': 'Place 87', 'destination': 'Bali', 'price': 120},
  {
    'image': '10.jpg',
    'place': 'Place 88',
    'destination': 'Boracay',
    'price': 110,
  },
  {
    'image': '11.jpg',
    'place': 'Place 89',
    'destination': 'Langkawi',
    'price': 75,
  },
  {
    'image': '12.jpg',
    'place': 'Place 90',
    'destination': 'Phu Quoc',
    'price': 68,
  },
  {
    'image': '13.jpg',
    'place': 'Place 91',
    'destination': 'Hoi An',
    'price': 55,
  },
  {
    'image': '14.jpg',
    'place': 'Place 92',
    'destination': 'Siem Reap',
    'price': 60,
  },
  {'image': '15.jpg', 'place': 'Place 93', 'destination': 'Hanoi', 'price': 50},
  {
    'image': '16.jpg',
    'place': 'Place 94',
    'destination': 'Ho Chi Minh City',
    'price': 45,
  },
  {
    'image': '17.jpg',
    'place': 'Place 95',
    'destination': 'Yangon',
    'price': 38,
  },
  {
    'image': '18.jpg',
    'place': 'Place 96',
    'destination': 'Colombo',
    'price': 42,
  },
  {'image': '19.jpg', 'place': 'Place 97', 'destination': 'Male', 'price': 210},
  {
    'image': '20.jpg',
    'place': 'Place 98',
    'destination': 'Rangoon',
    'price': 33,
  },
  {
    'image': '21.jpg',
    'place': 'Place 99',
    'destination': 'Lhasa',
    'price': 120,
  },
  {
    'image': '22.jpg',
    'place': 'Place 100',
    'destination': 'Ulaanbaatar',
    'price': 80,
  },
];
